version: '3.8'

services:
  app:
    build:
      context: .
      target: development

    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
      - DB_DATABASE=book_api3
    volumes:
      - .:/app

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: book_api3
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  pg_data:
